# This is a basic workflow to help you get started with Actions

name: Push to public repo

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.YOUR_SECRET_KEY }} 
          fetch-depth: 0
      - name: Push to public repo
        run: |
          git config --global user.name 'Nils Winter'
          git config --global user.email 'nilswinter@users.noreply.github.com'
          git checkout master
          git remote set-url origin https://x-access-token:${{ secrets.YOUR_SECRET_KEY }}@github.com/NilsWinter/mirror-test-2       
          git push --force origin master


